---
server.port: 8080
spring:
  graphql.graphiql:
    enabled: true
    path: /graphiql
  data.mongodb:
    host: localhost
    port: 27017
    database: recommendation-db
---
spring.config.activate.on-profile: docker
spring.data.mongodb.host: mongodb